### PR TITLE
Fix a bug where cronet_http sends incorrect HTTP request methods

### LINKED ISSUE #1053: `CronetClient` didn't setup proper method for requests
*(downstream https://github.com/cfug/dio/issues/2035)*

When making requests with the `DELETE` method, `POST` was sent instead. This is caused by the missing request method setup before we start the builder.
https://github.com/dart-lang/http/blob/9fb4cfa088f1bacdcd5a5154faa8e450ab06373d/pkgs/cronet_http/lib/src/cronet_client.dart#L315-L320

Instead, we can write:
```diff
  final builder = engine.newUrlRequestBuilder(
    request.url.toString().toJString(),
    jb.UrlRequestCallbackProxy.new1(
        _urlRequestCallbacks(request, responseCompleter)),
    _executor,
- );
+ ).setHttpMethod(request.method.toJString());
```

### PR DESCRIPTION
**Pull request by brianquinlan**
- `package:cronet_http` was always sending the "GET" HTTP request method, even for methods like `client.post`
- Thanks to @AlexV525 and @kientux for fixes!
- Fixes #1053

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

File: pkgs/http_client_conformance_tests/lib/src/request_methods_tests.dart [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+    setUpAll(() async {
+      httpServerChannel = await startServer();
+      httpServerQueue = StreamQueue(httpServerChannel.stream);
+      host = 'localhost:${await httpServerQueue.next}';
+    });
+    tearDownAll(() => httpServerChannel.sink.add(null));
+
+    test('custom method', () async {
+      await client.send(Request(
+        'CUSTOM',
```
Comment (AlexV525) [inline pkgs/http_client_conformance_tests/lib/src/request_methods_tests.dart:30]: Should we test case-sensitive method too?

Comment (brianquinlan) [reply pkgs/http_client_conformance_tests/lib/src/request_methods_tests.dart:30]: The problem is that IOClient would not pass that test because it always uppercases the request method:
https://github.com/dart-lang/sdk/blob/0b10bfcde99def6c43d4a306c920ba1ba855d058/sdk/lib/_http/http_impl.dart#L2791

This seems like a bug according to RFC-7232: https://www.rfc-editor.org/rfc/rfc7231#section-4.1

I will add a case-insensitive test and then a flag to disable it.

File: pkgs/cronet_http/CHANGELOG.md [hunk 2]
```diff
@@ -1,8 +1,7 @@
-## 0.4.3-wip
-
 ## 0.4.2
 
 * Require `package:jni >= 0.7.2` to remove a potential buffer overflow.
+* Fix a bug where incorrect HTTP request methods were sent.
```
Comment (devoncarew) [inline pkgs/cronet_http/CHANGELOG.md:4]: I assume `0.4.2` hasn't been published yet?

File: pkgs/http/test/io/client_conformance_test.dart [hunk 3]
```diff
@@ -10,5 +10,8 @@ import 'package:http_client_conformance_tests/http_client_conformance_tests.dart
 import 'package:test/test.dart';
 
 void main() {
-  testAll(IOClient.new);
+  testAll(IOClient.new,
+      preservesMethodCase:
+          false // https://github.com/dart-lang/sdk/issues/54187
```
Comment (devoncarew) [inline pkgs/http/test/io/client_conformance_test.dart:15]: nit: perhaps move this comment up a line to get better formatting?

**Review by devoncarew — APPROVED** [review]

File: pkgs/cronet_http/CHANGELOG.md (hunk 2 above)
Comment (brianquinlan) [reply pkgs/cronet_http/CHANGELOG.md:4]: Correct.

File: pkgs/http/test/io/client_conformance_test.dart (hunk 3 above)
Comment (brianquinlan) [reply pkgs/http/test/io/client_conformance_test.dart:15]: I used a shorter link to fit it on the same line.

**Comment by AlexV525** [comment]
@brianquinlan Could you also publish a new version of `cronet_http_embedded`? It's been outdated for a while. (Also see https://github.com/dart-lang/http/issues/1047)
